server.port: 8082
spring.application.name: payment-service

# Defines the success rate for processed payments.
# Valid values: 0 to 100.
# 0 means all payments will fail.
# 100 means all payments will be processed successfully.
# A value in (0, 100) simulates a random success rate.
# For example, 70 simulates a 70% success rate.
# Note: the value is evaluated randomly before each payment.
payment.success.rate: ${PAYMENT_SUCCESS_RATE:99}

otel:
  service.name: payment-service
  exporter.otlp.endpoint: http://localhost:4318

# Logging configuration that adds trace and span IDs to logs.
# This is useful for correlating logs across services.
# Note: this setting is not defined by the default Spring logging configuration
#      (spring-boot-starter-logging), but by Micrometer's default configuration
#      (micrometer-core). Micrometer supports metrics, tracing, and logging for Java applications.
#      (https://micrometer.io/)
logging.pattern.correlation: '[%32X{trace_id}-%16X{span_id}] '
