{
 "title": "Metrics - Service A",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(upload_file_total{service_name=\"service-a\"}[$__rate_interval]))",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(upload_file_total{service_name=\"service-a\", result=\"error\"}[5m])) / (sum(rate(upload_file_total{service_name=\"service-a\"}[5m])))",
     "legendFormat": "Error rate"
    }
   ]
  },
  {
   "title": "Latency P95",
   "type": "stat",
   "description": "Response time below which 95% of requests are completed.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(upload_file_duration_milliseconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total upload count",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(upload_file_total{service_name=\"service-a\", result=\"success\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentis",
   "type": "timeseries",
   "description": "Actual upload behavior (median, p95, p99).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(upload_file_size_bytes_bucket{service_name=\"service-a\"}[5m])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(upload_file_size_bytes_bucket{service_name=\"service-a\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(upload_file_size_bytes_bucket{service_name=\"service-a\"}[5m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}